### ISSUE TITLE
Not saving speed on netflix

### ISSUE THREAD

**Issue by arikroc** [igrigorik/videospeed#233]
Just noticed this started happening in the past day or two.

After changing episodes using the episode selector on netflix, it appears to reset the speed

Using latest version of chrome stable channel on MacOS

**Comment by igrigorik** [comment]
Please try restarting Chrome, we released new version of the plugin a few days ago.. a clean restart often cures most of these. If not, check your options for the checked flag, and reopen if problem persists.

**Comment by arikroc** [comment]
@igrigorik Can you re-open? I made sure the option was checked (it was), then restarted chrome twice, and it's still an issue. Chrome extensions page lists version 0.4.8

Steps to repro: set speed on netflix, and then refresh the page - it'll go back to 1.00

**Comment by igrigorik** [comment]
sg, let's dig a bit deeper here..

**Comment by igrigorik** [comment]
Huh, interesting.. The extension saves and initializes the prefs correctly, the issue is that netflix is doing something really odd in the unload step of the page and overrides the video speed to "1.0", which then gets persisted and hence the behavior.

**Comment by igrigorik** [comment]
Ok, think I have a patch that fixes it.. 

```diff
diff --git a/inject.js b/inject.js
index 7c5dac3..07881a9 100644
--- a/inject.js
+++ b/inject.js
@@ -69,10 +69,14 @@ chrome.extension.sendMessage({}, function(response) {
       });

       target.addEventListener('ratechange', function(event) {
-        var speed = this.getSpeed();
-        this.speedIndicator.textContent = speed;
-        tc.settings.speed = speed;
-        chrome.storage.sync.set({'speed': speed});
+        if (event.target.readyState > 0) {
+          var speed = this.getSpeed();
+          this.speedIndicator.textContent = speed;
+          tc.settings.speed = speed;
+          chrome.storage.sync.set({'speed': speed}, function() {
+            console.log('Speed setting saved: ' + speed);
+          });
+        }
       }.bind(this));

       target.playbackRate = tc.settings.speed;
```

However, I want to poke around on other sites with this first to see if it breaks anything.. If you're willing to take it for a spin, that'd be great too. :)

**Comment by arikroc** [comment]
Awesome! Definitely :) 

How would I do that? You make a new branch or upload a modified release, then I uninstall the current version of the extension and manually install the new one?

**Comment by igrigorik** [comment]
@arikroc made a separate branch @ https://github.com/igrigorik/videospeed/pull/237. You can checkout that branch locally and then install it as "unpacked extension": https://stackoverflow.com/questions/24577024/install-chrome-extension-not-in-the-store. A little involved, but hopefully that works.

**Comment by arikroc** [comment]
Ok, installed. Will keep you posted. No news from me is probably good news i.e. that it hasn't broken on any other sites :)
Works on netflix and youtube

**Comment by penguin8or** [comment]
I've also noticed this happen with autoplay videos on steam (web version)

**Comment by igrigorik** [comment]
@penguin8or thanks for the heads up. Would you, by any chance, be willing to install the branch and give it a shot as well?

**Comment by arikroc** [comment]
@igrigorik  I'm not sure how to repro yet but I've noticed the speed get reset to 1.0 a few times

**Comment by arikroc** [comment]
I've noticed speed reset again. I was just watching a video on reddit.com/r/videos, and it was at 1.0

I'm not sure how to repro. I did restart my computer recently, so maybe that played a role.

**Comment by fent** [comment]
This happens to me with Plex when loading new video, and even after seeking in the same video. The patch fixes it.

**Comment by igrigorik** [comment]
Copying from #240:

> When there are multiple videos, changing speed applies to all of them, but when loading new videos it sometimes just resets to 1.0x (despite having 'Remember Playback Speed' enabled).
I wasn't able to reproduce exactly what happens - sometimes some videos in between also get a speed of 0.0x (or last speed - 1).

**Comment by fent** [comment]
Adding onto my previous message, the patch does work, but it also prevents me from changing the speed while the video is loading. It would be nice if it changed the speed only if the user intended it (by pressing one of the buttons on the controller keyboard shortcuts), and not from some other non-user event.

**Comment by igrigorik** [comment]
@fent in theory, that's what [event.isTrusted](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted) is for. In practice, however, it doesn't appear to flag the right cases -- if I add an "or" for that, Netflix reverts to same behavior as before.

That said, as an idea, an ugly hack...
```
diff --git a/inject.js b/inject.js
index 1403bd6..b79357b 100644
--- a/inject.js
+++ b/inject.js
@@ -71,7 +71,8 @@ chrome.extension.sendMessage({}, function(response) {
       target.addEventListener('ratechange', function(event) {
         // Ignore ratechange events on unitialized videos.
         // 0 == No information is available about the media resource.
-        if (event.target.readyState > 0) {
+        if (event.target.readyState > 0 || userAction) {
+          userAction = false;
           var speed = this.getSpeed();
           this.speedIndicator.textContent = speed;
           tc.settings.speed = speed;
@@ -310,6 +311,7 @@ chrome.extension.sendMessage({}, function(response) {
       });
   }

+  var userAction = false;
   function runAction(action, document, keyboard) {
     var videoTags = document.getElementsByTagName('video');
     videoTags.forEach = Array.prototype.forEach;
@@ -326,11 +328,13 @@ chrome.extension.sendMessage({}, function(response) {
         } else if (action === 'advance') {
           v.currentTime += tc.settings.advanceTime;
         } else if (action === 'faster') {
+          userAction = true;
           // Maximum playback speed in Chrome is set to 16:
           // https://cs.chromium.org/chromium/src/media/blink/webmediaplayer_impl.cc?l=103
           var s = Math.min( (v.playbackRate < 0.1 ? 0.0 : v.playbackRate) + tc.settings.speedStep, 16);
           v.playbackRate = Number(s.toFixed(2));
         } else if (action === 'slower') {
+          userAction = true;
           // Audio playback is cut at 0.05:
           // https://cs.chromium.org/chromium/src/media/filters/audio_renderer_algorithm.cc?l=49
           // Video min rate is 0.0625:
@@ -355,6 +359,7 @@ chrome.extension.sendMessage({}, function(response) {
   }

   function resetSpeed(v, target) {
+    userAction = true;
     if (v.playbackRate === target) {
       v.playbackRate = tc.settings.resetSpeed;
     } else {
```

Any chance you could try that patch on top of the previous one? Does it solve your case? I'm having a hard time reproducing the condition on this end.

**Comment by fent** [comment]
It doesn't. If the video is not yet initialized, I'm able to change the speed, but it resets to 1.0 right before the change. If I wait until the video initializes to change the speed, then it is changed correctly.

I think the `video.playbackRate` is set to 1.0 if the video is not yet initialized.

**Comment by igrigorik** [comment]
@fent I merged the earlier patch, let's continue the uninitialized case in a separate thread.

**Comment by fent** [comment]
Ok. Should I create an issue for it?

**Comment by igrigorik** [comment]
Yep, please do!

**Comment by arikroc** [comment]
@igrigorik I saw that this was merged into master, so I deleted the modified extension I'd installed from you a while back and re-installed from chrome store.

Then the netflix issue came back, so I tried reinstalling from both master and the original modified extension I'd installed, but in both cases the netflix issue is back. Tried restarting chrome too.

I also tried redownloading, deleting the extension, and installing from the readystate branch again but still have the netflix issue back again.

Any ideas Ilya?

**Comment by igrigorik** [comment]
Hmm, running latest version from master.. I can't reproduce this, the speed is not reset when I reload or load a new video.

**Comment by arikroc** [comment]
@igrigorik Is this true even for videos on netflix?

**Comment by arikroc** [comment]
@igrigorik I made a mistake! When I installed the new extension, I guess it wiped the "remember speed setting." My apologies.

**Comment by igrigorik** [comment]
@arikroc phew, good -- glad you got it working!
