### ISSUE TITLE
not working on https://pan.baidu.com

### ISSUE THREAD

**Issue by wangbuyao** [igrigorik/videospeed#523]
im sure the video is HTML5  and this extension runs well on any other web

**Comment by jacobcolbert** [comment]
Is there a way to view a video without an account? Can you link directly to
such a video?

**Comment by wangbuyao** [comment]
https://pan.baidu.com/s/1tfW8rR8RY-nCV75qUKZDZQ&nbsp;
Code：Sze3&nbsp;


thx！


发自我的iPhone


------------------ Original ------------------

**Comment by jacobcolbert** [comment]
Thanks. It works perfectly for me though! Can you open up the console
(Ctrl+shift+J) and let me know if you get any errors?

**Comment by jacobcolbert** [comment]
Can you copy and paste them? I can't figure out what is wrong easily since
on my end it is working fine.

**Comment by wangbuyao** [comment]
I'm sorry for disturbing u.I can hardly understand this puzzle


Service worker active
2userscript.html?id=2b5e4d5f-1e1b-454e-a5a1-637c1ad47fe4:514 waiting
/feproxy/ad/list?list%5B0%5D%5Bid%5D=web-text&list%5B0%5D%5Bw%5D=0&list%5B0%5D%5Bh%5D=0&uk=1655457047&channel=chunlei&web=1&app_id=250528&bdstoken=33cab4479ac5694165b8588905da6c4c&logid=MTU2OTk0Mzk4MDE3MzAuNTA3MjgxNTkwMjI2ODA1NQ==&clienttype=0:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
wappass.baidu.com/v3/login/api/auth?return_type=3&tpl=netdisk&u=https%3A%2F%2Fpcsdata.baidu.com%2Frest%2F2.0%2Fpcs%2Ffile%3Ffrom_module%3Dcloud-ui%26ssnerror%3D0%26errno%3D3%26type%3Dstoken%26traceid%3D%26method%3Dplantcookie%26source%3Dpcsdata%26callid%3D0.1%26errmsg%3Dunknow%2520error%28110001%29%26bduss%3D%26stoken%3D%26logid%3D6354407014121910161&notjump=1&traceid=:1 Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
wappass.baidu.com/v3/login/api/auth?return_type=3&tpl=netdisk&u=https%3A%2F%2Fpcs.baidu.com%2Frest%2F2.0%2Fpcs%2Ffile%3Ffrom_module%3Dcloud-ui%26ssnerror%3D0%26errno%3D3%26type%3Dstoken%26traceid%3D%26method%3Dplantcookie%26source%3Dpcs%26callid%3D0.1%26errmsg%3Dunknow%2520error%28110001%29%26bduss%3D%26stoken%3D%26logid%3D6354407046934820710&notjump=1&traceid=:1 Failed to load resource: net::ERR_TOO_MANY_REDIRECTS





------------------ 原始邮件 ------------------
发件人: "jacobcolbert"<notifications@github.com>;
发送时间: 2019年10月1日(星期二) 晚上11:32
收件人: "igrigorik/videospeed"<videospeed@noreply.github.com>;
抄送: "大王自己来巡山"<602666372@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [igrigorik/videospeed] not working on https://pan.baidu.com(#523)



Can you copy and paste them? I can't figure out what is wrong easily since
 on my end it is working fine.

**Comment by jacobcolbert** [comment]
Hmm none of that seems to be about this extension from what i can tell. You can filter to 'inject.js' and see if that still comes up with errors. 

What do you mean by not working? Does the overlay with the speed show up in the top corner?

**Comment by wangbuyao** [comment]
The overlay with the speed doesn't show up on this web and there is no response when i click shortcut keys to control the video speed. I will make a screen recording tomorrow if u need.



发自我的iPhone


------------------ Original ------------------

**Comment by wangbuyao** [comment]
Ok. Now i have to go sleep. Thank you very much for helping me！



发自我的iPhone


------------------ Original ------------------

**Comment by wangbuyao** [comment]
I'm sorry that the email with the video is too big to send out.
I have input 'inject.js'  and it comes to "no matching property" . It  seems that this extension is not running on this particular website at all. Maybe it's because adjusting video speed in this website is a charging service and some restrictions have been imposed on me domestic users？







------------------ 原始邮件 ------------------
发件人: "jacobcolbert"<notifications@github.com>;
发送时间: 2019年10月2日(星期三) 凌晨0:03
收件人: "igrigorik/videospeed"<videospeed@noreply.github.com>;
抄送: "大王自己来巡山"<602666372@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [igrigorik/videospeed] not working on https://pan.baidu.com(#523)




That could be helpful. Please open the console for it.

**Comment by Songkeys** [comment]
@jacobcolbert 

I just found the problem and got here.

The blight is that this site is using a shadow-root to contain videos.

![image](https://user-images.githubusercontent.com/22665058/67792221-b2873f80-fa70-11e9-95cf-de91bec3d88c.png)

More specifically, it uses "closed" shadow-root to prevent end-user to access the node. So, the basic script is not able to detect the video element in the hidden document.

To crack this, we need make the "closed" shadow-root "open", and then recursively check potential shadow-root's and their children in the current page as well.

To open the shadow-root, one trick is to inject custom script in the head of the document which re-defines the `Element.prototype.attachShadow()` behavior to prevent the site calling `el.attachShadow({ mode: 'closed' })` taking effects.

(I don't know if there's any other video websites doing so, but the reason the site holding back the videos like this is that the speedup feature is a premium service requiring payment. Anyway...)

**Comment by ChadBailey** [comment]
This is a great report - and good evidence that our efforts to make a generic solution to #540  was worth the effort. A fix is currently being pursued, hopefully it will become available soon.

**Comment by wangbuyao** [comment]
Ok.Thank you very much for your efforts！



发自我的iPhone


------------------ Original ------------------

**Comment by ChadBailey** [comment]
Do you have an updated link I can try? The one you posted before is no longer working

**Comment by wangbuyao** [comment]
https://pan.baidu.com/play/video#/video?path=%2F2020%E5%BE%90%E6%B6%9B%2F05.%E6%AF%9B%E4%B8%AD%E7%89%B9%2F01-%E5%AF%BC%E8%AE%BA%E4%B8%8E%E6%AF%9B%E6%B3%BD%E4%B8%9C%E6%80%9D%E6%83%B3%E7%9A%84%E5%BD%A2%E6%88%90%E4%B8%8E%E5%8F%91%E5%B1%95-1.mp4



发自我的iPhone


------------------ Original ------------------

**Comment by ChadBailey** [comment]
Sorry I can't seem to get it to work... looks like it's asking to log in or use an app? It's difficult to tell since having to use a translator

**Comment by Songkeys** [comment]
@ChadBailey 
Try this one..?
https://pan.baidu.com/s/1wmsOcea9PX7q-Uu0nSFY8w
Password: `9kss`

**Comment by wangbuyao** [comment]
This one works！So is there any problem with the particular video i sent you？



发自我的iPhone


------------------ Original ------------------

**Comment by wangbuyao** [comment]
Im sorry i just checked my email so i didnt reply in time.



发自我的iPhone


------------------ Original ------------------

**Comment by ChadBailey** [comment]
It's fine, I probably wouldn't have gotten to it either way... I am on my way to work now so I will have to look at it later. Thanks for the prompt responses!

**Comment by wangbuyao** [comment]
You are very kind. Im not in a hurry. Thank you for your responsibility.




------------------ Original ------------------

**Comment by igrigorik** [comment]
@wangbuyao @ChadBailey thanks for working on this one. 

Closing due to lack of activity but please reopen if there is more to investigate.

**Comment by ChadBailey** [comment]
For context that I didn't mention before, this appears to be impacted by the bug that impacts appleTV. It should be fixed when PR https://github.com/igrigorik/videospeed/pull/541 gets implemented

**Comment by ChadBailey** [comment]
Although this has been merged, it has not been confirmed to have fixed the problem so I am re-opening. I don't think the official distribution has caught up yet so the fix hasn't been pushed out to the clients yet (afaik). I'll post again to have you confirm it's fixed once those changes have been pushed.

**Comment by wangbuyao** [comment]
Fine. Thank you very much.



发自我的iPhone


------------------ Original ------------------

**Comment by ChadBailey** [comment]
This may be fixed in the latest version just release v0.6.1. Can you check it out and validate if it's fixed for me?

**Comment by Songkeys** [comment]
> This may be fixed in the latest version just release v0.6.1. Can you check it out and validate if it's fixed for me?

@ChadBailey sadly not fixed.


![image](https://user-images.githubusercontent.com/22665058/77789067-467a2900-705a-11ea-98d5-2d24a2c76186.png)


By calling `getShadow`, the real shadow root seems to be skipped?https://github.com/igrigorik/videospeed/blob/master/inject.js#L439-L456

I'm not sure but can you confirm that the `closed` shadow root is accessible?

I think we need to modify the web API `apiElement.prototype.attachShadow()` to force it to create an open shadow root?

Check https://github.com/igrigorik/videospeed/issues/523#issuecomment-547542977

**Comment by ChadBailey** [comment]
interesting, thanks for all the detailed information. i'll change the labels and hopefully someone can get it fixed. i'll take a swing at it if no one has by the time i get the chance
