### ISSUE TITLE
Remember controller position for its corresponding site

### ISSUE THREAD

**Issue by FedeCuci** [igrigorik/videospeed#973]
I'm not sure if this would be possible to implement, but it would be useful if the controller location is rememebred for specific sites. For example, if I move the controller to the bottom left for Youtube, I'd like it to be there in that position again for the next time, but only for that speicific site. So if I move the controller on Youtube, it only remembers that position for Youtube, but if I move somewhere else on Netflix, it only remembers that position on Netflix. I think this would be useful because many videos on Youtube have the "Includes paid promotion" banner at the top left, which overlaps the controllers default location. Same goes for Netflix's "back arrow". I provided an image to show what I mean.

Youtube:
![image](https://user-images.githubusercontent.com/19730248/194709463-18669748-88ca-45b7-8adb-19d4fca260c7.png)

Netflix:
![image](https://user-images.githubusercontent.com/19730248/194709653-fab43cd9-7031-4249-862f-9be6fb6f1713.png)

**Comment by magnus-ISU** [comment]
To provide more information, this is caused because the extension inserts the controls in a bad layer of divs. I fixed this in my firefox fork, without adding the proposed feature, by making it always put the speed bubble over the "includes paid promotion box".

It's in line 353 of inject.js in my pull request https://github.com/igrigorik/videospeed/pull/907/files which has been ignored for over a year now.

Seeing as my fork solves several issues recently commented on in here and these issues stay unfixed despite the refactoring efforts of igrigorik, I tried now to upload it to some chromium extension store, but it seems that is a nontrivial process; you have to pay $5 to do it for google which I will not do at the moment, Microsoft's process for the edge store wouldn't work for me, and Opera only lets you install their extensions on opera which is pretty stupid. Luckily you can download the extension file from mozilla and add it as a local extension, and it works on chrome without any issue; I'm using it on Brave when I want to use a chromium browser because I still like fast playback.

If you want I can give more detailed instructions for installing the fork if you are interested and cannot figure it out.

As for whether I think the proposed feature should be implemented, I'm unsure; currently, the extension only stores a small amount of preferences and this would mean it would be using a lot more storage probably; and I also know because I had to rewrite the whole thing that the current code for how settings are handled is actual trash.

**Comment by FedeCuci** [comment]
Hi Magnus, sorry for the late reply, I tend to forget to check Github notifications. Anyway, I have tested your fork on Firefox and indeed it works very nicely! The controller is on top of the "Includes paid promotion" box on Youtube as well as on top of the "Back arrow" on Netflix. In fact, this solution is even better than what I proposed given the tradeoff that you mentioned of complexity for features. I don't see why your pull request should not be merged as this makes the extension much more usable. I'll make sure to leave a comment there as well. I guess I can close this issue with your PR as a solution to it. Let me know 👍

**Comment by magnus-ISU** [comment]
Issue still exists upstream so I wouldn't close

**Comment by FedeCuci** [comment]
Okay, I'll leave it open 👍

**Comment by jb510** [comment]
Found this old issue before reporting the same problem, "overlap of Includes Paid Promotion".  I didn't even realize you could move the controller label, but was sad to see it still doesn't remember where it's been moved it.
